[package]
name = "gol_cpu_bench"
version = "0.1.0"
authors = ["romenjelly"]
edition = "2018"

[dependencies]
crossbeam-queue = "0.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.8"
num_cpus = "1.13"
terminal_size = "0.1.17"
crossterm = "0.23.0"
